version: '3'
services:
  # jenkins:
  #   container_name: jenkinsci
  #   build:
  #     context: ./docker/jenkins
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
  #   volumes:
  #     - ./volumes/jenkins:/var/jenkins_home
  #   networks:
  #     - jenkins
    
  jfrog:
    container_name: jfrog-artifactory
    build:
      context: ./docker/jfrog
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./volumes/jfrog:/var/opt/jfrog/artifactory
    networks:
      - jenkins
      
networks:
  jenkins:
    driver: bridge
